#pragma once
enum SupportedEmbeddingModels {
    FLOCKMTL_TEXT_EMBEDDING_3_SMALL = 0,
    FLOCKMTL_TEXT_EMBEDDING_3_LARGE,
    FLOCKMTL_UNSUPPORTED_EMBEDDING_MODEL,
    FLOCKMTL_SUPPORTED_EMBEDDING_MODELS_COUNT
};